### ISSUE TITLE
Focus Issue: 1.0 release tasks

### ISSUE THREAD

**Issue by ehmatthes** [django-simple-deploy/django-simple-deploy#212]
It would be easy to stay at a pre-1.0 release for years, but people are right to be skeptical of adopting a project that's unwilling to declare that it's stable and reliable. This is a meta-issue to collect the specific tasks that are highest priority in getting to a 1.0 release.

Essential 1.0 tasks.

- [ ] Deployment works on all three currently supported platforms, and all three OSes.
- [x] Output is clean and consistent enough for people to show in learning resources.
- [x] Friendly logs/ summaries work for all three platforms. (post 1.0)
- [x] Write a stability policy. #214 (Moved to parking lot #337)
- [x] Write a "for authors/creators" doc. (parking lot)
- [x] Review open issues and flag any that are critical for a 1.0 release.
- [x] Make a 0.9.0 release that's essentially a 1.0 candidate release, with a set date for making a 1.0 release. (No, it's been close to 1.0 for long enough now.)
- [x] Sort out ability to push more than one project to Fly.
- [x] Break this into a plugin model.
- [x] Audit `hookspecs.py` and `deploy.py`. Are these hooks stable enough for the 1.0 series? Are there any that should be consolidated? Are there any that should be renamed/ refactored/ written? #393
- [x] Document all functions and methods in plugin_utils. When making dsd-codered, I knew there was a utility for adding a new dir to the user's project. That's not an obvious capability. #391

**Comment by ehmatthes** [comment]
Nice to have 1.0 tasks
---

- [ ] Identify a second maintainer, who can make releases.

**Comment by ehmatthes** [comment]
Supporting all OSes
---

- [ ] Windows
    - [ ] heroku
    - [ ] fly_io
    - [ ] platform_sh

**Comment by ehmatthes** [comment]
Misc
---

- [ ] Should change app name to `django-simple-deploy`, so users only ever type "django-simple-deploy", or "deploy", never "simple_deploy".

**Comment by ehmatthes** [comment]
Final documentation update
---

- [ ] Update roadmap section, which is entirely focused on reaching 1.0 at this point.

**Comment by ehmatthes** [comment]
Open tasks moved to #398.
