### ISSUE TITLE
Implement a plugin model

### ISSUE THREAD

**Issue by ehmatthes** [django-simple-deploy/django-simple-deploy#313]
This project can only reach its full potential through the implementation of a plugin model. That said, the fact that this involves configuration for deployment means there are security implications. A pretty careful approach to facilitating a plugin model is warranted.

There are other, simpler 1.0 tasks to close out. But closing those out after implementing the plugin model will help make sure that new architecture is done appropriately.

After implementing the internal plugin model, we should do as much refactoring as possible before splitting out into external plugins. Right now, any change that affects both a plugin and core is contained in a single release. After separating into external plugins, that would require at least two releases, and four releases if it affects core and all plugins. The benefit will be that individual plugins can be developed and released on their own schedule from that point forward.

- [x] Research [pluggy](https://pluggy.readthedocs.io/en/latest/).
- [x] See [datasette](https://github.com/simonw/datasette) as an example.
- [x] Consider using ABCs to enforce structure? See #283. Don't need, just require that specific hooks are implemented.
- [x] General process:
    - [x] Implement an internal plugin model.
        - [x] Move platform-specific code to isolated subdirs. #325
        - [x] Refine internal plugins; move PlatformDeployer to separate file, some cleanup. #326 
        - [x] Uncouple tests from core. #330
    - [x] Complete as much internal refactoring as is clearly needed. Once plugins are separated, any changes that affect plugin and core will require at least two releases; four releases if it affects all platforms.
    - [x] Move this project to an org.
    - [x] Implement an external plugin model, where plugins are pulled out into separate repos. ~~Unit tests should work in the standalone repo~~, integration tests and e2e tests should only run when core is available. See #361.
    - [ ] Refine to the point it can support third-party plugins with a clear integration process.
    - [ ] Announce.
- [ ] Write a brief ADR.

**Comment by ehmatthes** [comment]
Working notes
---

- [ ] See unfinished tasks in #319.

**Comment by ehmatthes** [comment]
External plugin notes
---

- [ ] Probably change name of `--platform` flag to `--plugin` flag? How does the availability of more than one plugin per platform affect the user interface, and documentation?

**Comment by ehmatthes** [comment]
More notes
---

- [ ] Require the three main plugins in core.

**Comment by ehmatthes** [comment]
All critical tasks here are finished, noncritical tasks moved to parking lot.
