### ISSUE TITLE
Move plugins to separate repos

### ISSUE THREAD

**Issue by ehmatthes** [django-simple-deploy/django-simple-deploy#361]
This is a continuation of #360, which was overly focused on separating out the Fly.io plugin. They all need to be dealt with in one move.

Functionality
---

- [x] Run platform-specific integration tests. #362
- [x] Run platform-specific e2e tests. #363
- [x] Push plugins to PyPI.
- [x] Require plugins in dsd config.
- [x] Test against PyPI versions, for a manual push.
- [x] Make a new release for dsd.
- [x] Announce: theoretically, anyone could write a new plugin named `dsd-platformname-<optional-extension>`. Install dsd and plugin, run `manage.py simple_deploy --platform platform_name`, and that plugin will be auto-discovered and run. If you want to improve fly deployments, you only need to contribute to dsd-flyio, not core dsd.
- [x] Should plugins require django-simple-deploy? (Yes, then you can just install the plugin you're interested in. Also, you can't import the plugin module without simple_deploy being installed.)

Documentation
---

- [ ] Update core docs.
    - [ ] Make a page/entry with detailed notes about plugins, starting with notes in this [comment](https://github.com/django-simple-deploy/django-simple-deploy/issues/356#issuecomment-2450715972) from #356.
- [x] Create simple readmes for each of the plugins.
- [x] Announce.

**Comment by ehmatthes** [comment]
Test against PyPI plugins
---

- [ ] Fix issue with templates not being in dist/. #367
